/**
 * render() — turn normalized OrgActivity into a human-readable standup.
 *
 * Phase 2 is the *mechanical* renderer: deterministic markdown straight from the
 * activity, no AI. It doubles as the fallback when no Anthropic key is set, and
 * as the ground truth the Phase 3 summarizer is checked against. Output is
 * Discord-flavored markdown; the delivery layer handles chunking.
 */
import type { OrgActivity, PersonActivity } from './types.js';

function fmtNum(n: number): string {
  return n.toLocaleString('en-US');
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

/** A compact one-line stats summary, omitting zero-valued parts. */
function statLine(p: PersonActivity): string {
  const t = p.totals;
  const parts: string[] = [];
  if (t.commits) parts.push(`${t.commits} commit${t.commits === 1 ? '' : 's'}`);
  if (t.additions || t.deletions) parts.push(`+${fmtNum(t.additions)}/−${fmtNum(t.deletions)}`);
  const prBits: string[] = [];
  if (t.prsOpened) prBits.push(`${t.prsOpened} opened`);
  if (t.prsMerged) prBits.push(`${t.prsMerged} merged`);
  if (prBits.length) parts.push(`PRs: ${prBits.join(', ')}`);
  if (t.reviewsGiven) parts.push(`${t.reviewsGiven} review${t.reviewsGiven === 1 ? '' : 's'}`);
  const issueBits: string[] = [];
  if (t.issuesOpened) issueBits.push(`${t.issuesOpened} opened`);
  if (t.issuesClosed) issueBits.push(`${t.issuesClosed} closed`);
  if (issueBits.length) parts.push(`issues: ${issueBits.join(', ')}`);
  if (t.repos > 1) parts.push(`${t.repos} repos`);
  return parts.join(' · ');
}

/** Up to `limit` notable lines for a person: merged PRs first, then opened, then commits. */
function highlights(p: PersonActivity, limit = 6): string[] {
  const lines: string[] = [];
  const merged = p.pullRequests.filter((pr) => pr.state === 'merged');
  const opened = p.pullRequests.filter((pr) => pr.state !== 'merged');

  for (const pr of merged) lines.push(`✅ merged [#${pr.number}](${pr.url}) ${pr.title} \`${pr.repo}\``);
  for (const pr of opened) {
    const tag = pr.state === 'draft' ? 'draft' : 'open';
    lines.push(`📂 ${tag} [#${pr.number}](${pr.url}) ${pr.title} \`${pr.repo}\``);
  }
  // If little PR activity, surface a few commit subjects so the person isn't blank.
  if (lines.length < 3) {
    for (const c of p.commits.slice(0, 3)) {
      lines.push(`• ${c.message} \`${c.repo}\``);
    }
  }
  const reviewed = p.reviews.length;
  if (reviewed) {
    lines.push(`👀 reviewed ${reviewed} PR${reviewed === 1 ? '' : 's'}`);
  }
  return lines.slice(0, limit);
}

export interface RenderOptions {
  /** Title prefix. Defaults to a calendar emoji + "Daily Standup". */
  title?: string;
}

/** Render the full mechanical standup as Discord-flavored markdown. */
export function renderMechanical(activity: OrgActivity, opts: RenderOptions = {}): string {
  const { org, window, people } = activity;
  const title = opts.title ?? '📋 Daily Standup';
  const day = fmtDate(window.until);
  const span =
    fmtDate(window.since) === day ? day : `${fmtDate(window.since)} → ${day}`;

  const out: string[] = [];
  out.push(`# ${title} — ${org}`);
  out.push(`**${span}** · ${people.length} contributor${people.length === 1 ? '' : 's'} active`);
  out.push('');

  if (people.length === 0) {
    out.push('_No GitHub activity in this window._');
    return out.join('\n');
  }

  for (const p of people) {
    const name =
      p.person.displayName && p.person.displayName !== p.person.login
        ? `${p.person.displayName} (\`${p.person.login}\`)`
        : `\`${p.person.login}\``;
    out.push(`## ${name}`);
    const stats = statLine(p);
    if (stats) out.push(`*${stats}*`);
    for (const line of highlights(p)) out.push(`- ${line}`);
    out.push('');
  }

  out.push('—');
  out.push('_Generated by Herald from GitHub activity. Reflects code activity only._');
  return out.join('\n').trimEnd() + '\n';
}
